dist: bionic

notifications:
  email:
    recipients:
      - hellojessemillar@gmail.com
    on_success: change
    on_failure: always

script:
  - curl -L https://github.com/becheran/mlc/releases/download/v0.9.1/mlc -o mlc
  - chmod +x mlc
  - ./mlc --ignore-links "*mh.jessemillar.com*" "*bulletjournal.com*"
